name: Mentor-Mentee App CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Lint Check
      run: npm run lint || echo "Linting issues found"
    
    - name: Build
      run: npm run build
    
    - name: Run Tests
      run: npm test || echo "Tests failed or not configured"

  backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Check database initialization
      run: |
        python -c "import sqlite3; conn = sqlite3.connect('mentor_mentee.db'); conn.close()"
    
    - name: Check API server startup
      run: |
        python -m pytest -xvs || echo "Tests failed or not configured"
