name: Mentor-Mentee App Deployment

on:
  workflow_run:
    workflows: ["Mentor-Mentee App CI"]
    types:
      - completed
    branches:
      - main
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Setting up environment for deployment"
        # 여기에 환경 설정 명령어를 추가하세요
    
    - name: Deploy Frontend
      run: |
        echo "Deploying frontend..."
        # 프론트엔드 배포 스크립트 실행
        cd frontend
        # 예시: npm run deploy 또는 다른 배포 명령어
    
    - name: Deploy Backend
      run: |
        echo "Deploying backend..."
        # 백엔드 배포 스크립트 실행
        cd backend
        # 예시: python deploy_script.py 또는 다른 배포 명령어
    
    - name: Send Deployment Notification
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "Deployment successful!"
        else
          echo "Deployment failed!"
        fi
        # 알림 서비스 연동 명령어를 추가할 수 있습니다
